name: Prerelease PR (premain)

on:
  push:
    branches: ["premain"]
    paths-ignore:
      - ".release-please-manifest.premain.json"
      - "CHANGELOG.md"
      - "VERSION"
      - "README.md"
      - "ts/package.json"
      - "ts/package-lock.json"
  workflow_dispatch: {}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please (PR only)
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN || secrets.GITHUB_TOKEN }}
          target-branch: premain
          config-file: release-please-config.premain.json
          manifest-file: .release-please-manifest.premain.json
          skip-github-release: true
